# Week 02 Lab: Image Processing Through a Four-Step Pipeline

**Course:** Perceptual Computing / Computer Graphics and Human-Computer Interaction  

## Student Information

- **Name: Muhammad Mutahhar**
- **Roll number: 2K24/CSE/104**

## Problem 1: Thresholding 

Turn each grayscale value into black (`0`) or white (`255`).

### Step 1: Inputs and output
Input: an image and a threshold number. Output: an image of only `0` and `255`.

### Step 2: Rule
If `pixel >= threshold`, output `255`. Otherwise output `0`.

### Step 3: Small example
For threshold `130`:

```text
140  205  80
100  210  45
```

Answer: `255 255 0` / `0 255 0`.

### Step 4: Python

In [10]:
import numpy as np

# TODO 1:
def threshold_image(image: np.ndarray, threshold: int) -> np.ndarray:
    return np.where(image >= threshold, 255, 0).astype(np.uint8)


rows = int(input("How many rows does your image have? "))

image_list = []
print("Enter each row's pixel values separated by spaces (e.g. 20 128 200):")
for i in range(rows):
    row_input = input(f"Row {i+1}: ")
    row = [int(x) for x in row_input.split()]
    image_list.append(row)

problem_1_input = np.array(image_list, dtype=np.uint8)

threshold = int(input("Enter the threshold value: "))

print("\nInput your expected result:\n")
#the functionailty to input expected result is used because expected result will be different for each input, so by using this you can achieve the exact comparision
expected_list = []
print("Enter each row's pixel values separated by spaces (e.g. 20 128 200):")
for i in range(rows):
    row_input = input(f"Row {i+1}: ")
    row = [int(x) for x in row_input.split()]
    expected_list.append(row)

problem_1_expected = np.array(expected_list, dtype=np.uint8)

result = threshold_image(problem_1_input, threshold)
print("\nOriginal image:\n", problem_1_input)
print("\nThresholded image:\n", result)


# TODO 2: 
np.testing.assert_array_equal(threshold_image(problem_1_input, threshold), problem_1_expected)
print("Problem 1 passed")

Enter each row's pixel values separated by spaces (e.g. 20 128 200):

Input your expected result:

Enter each row's pixel values separated by spaces (e.g. 20 128 200):

Original image:
 [[140 205  80]
 [100 210  45]]

Thresholded image:
 [[255 255   0]
 [  0 255   0]]
Problem 1 passed


## Problem 2: Image Memory

Calculate how many bytes an uncompressed image uses.

### Step 1: Inputs and output
Inputs: width, height, and bits per pixel (`bpp`). Output: memory in bytes.

### Step 2: Rule
`bytes = width * height * bpp / 8`

### Step 3: Small example
For `1240 x 786` and `30 bpp`: `1240 * 786 * 30 / 8 = 3,654,900` bytes.

### Step 4: Python

In [11]:
# TODO 1:
def display_memory_bytes(width: int, height: int, bpp: int) -> int:
    return width * height * bpp // 8


width = int(input("Enter width: "))
height = int(input("Enter height: "))
bpp = int(input("Enter bits per pixel (bpp): "))

result = display_memory_bytes(width, height, bpp)

#the functionailty to input expected result is used because expected result will be different for each input, so by using this you can achieve the exact comparision
expected_bytes = int(input("Enter Expected Bytes: "))

print(f"\nMemory required: {result} bytes")
print(f"\nMemory expected: {expected_bytes} bytes")

# TODO 2: 

assert result == expected_bytes
print("Problem 2 passed")


Memory required: 3654900 bytes

Memory expected: 3654900 bytes
Problem 2 passed


## Problem 3: Average 9 Pixels 

Find the average of a small `3 x 3` image block.

### Step 1: Inputs and output
Input: nine pixel values in a `3 x 3` array. Output: one rounded number.

### Step 2: Rule
`average = sum of all 9 values / 9`

### Step 3: Small example
```text
23 24 25
24 18 30
26 20 26
```
Sum = 216, so `216 / 9 = 24` (rounded).

### Step 4: Python

In [12]:
import numpy as np

# TODO 1:
def mean_filter_3x3(neighborhood: np.ndarray) -> int:
    """Return the rounded average of 9 pixels."""
    return round(np.sum(neighborhood) / 9)

print("Enter the 3x3 array, row by row (3 numbers separated by spaces):")
rows = []
for i in range(3):
    row_input = input(f"Row {i+1}: ")
    row = [int(x) for x in row_input.split()]
    rows.append(row)

user_array = np.array(rows, dtype=np.uint8)

#the functionailty to input expected result is used because expected result will be different for each input, so by using this you can achieve the exact comparision
expected_figure = int(input("Enter your expected average: "))

result = mean_filter_3x3(user_array)
print(f"\nArray:\n{user_array}")
print(f"\nAverage (rounded): {result}")
print(f"\nAverage (rounded): {expected_figure}")

# TODO 2: 
assert mean_filter_3x3(user_array) == expected_figure
print("\nProblem 3 passed")

Enter the 3x3 array, row by row (3 numbers separated by spaces):

Array:
[[23 24 25]
 [24 18 30]
 [26 20 26]]

Average (rounded): 24

Average (rounded): 24

Problem 3 passed


## Problem 4: Change Image Contrast

Change numbers from one range to another range.

### Step 1: Inputs and output
Input: an array and two ranges (old and new). Output: an array with the new values.

### Step 2: Rule
`new = (value - old_min) / (old_max - old_min) * (new_max - new_min) + new_min`

### Step 3: Small example
Change `[130, 140, 60]` from range `[0, 150]` to `[0, 255]`:
`130 -> 221`, `140 -> 238`, `60 -> 102`.

### Step 4: Python

In [13]:
import numpy as np

# TODO 1:
def contrast_stretch(
    image: np.ndarray,
    in_min: float,
    in_max: float,
    out_min: float,
    out_max: float,
) -> np.ndarray:
    new_values = (image - in_min) / (in_max - in_min) * (out_max - out_min) + out_min
    return np.clip(new_values, out_min, out_max)

values_input = input("Enter array values separated by spaces (e.g. 50 100 150): ")
image_list = [float(x) for x in values_input.split()]
user_image = np.array(image_list, dtype=np.float32)

in_min = float(input("Enter old range minimum (in_min): "))
in_max = float(input("Enter old range maximum (in_max): "))
out_min = float(input("Enter new range minimum (out_min): "))
out_max = float(input("Enter new range maximum (out_max): "))


result = contrast_stretch(user_image, in_min, in_max, out_min, out_max)

#the functionailty to input expected result is used because expected result will be different for each input, so by using this you can achieve the exact comparision
values_input = input("Enter expected values separated by spaces (e.g. 50 100 150): ")
image_list = [float(x) for x in values_input.split()]
expected = np.array(image_list, dtype=np.float32)

print(f"\nOriginal array: {user_image}")
print(f"Stretched array: {result}")
print(f"Expected array: {expected}")

# TODO 2:
np.testing.assert_allclose(result, expected)
print("Problem 4 passed")


Original array: [130. 140.  60.]
Stretched array: [221. 238. 102.]
Expected array: [221. 238. 102.]
Problem 4 passed


## Problem 5: Find an Edge with Sobel 

Use a Sobel filter to find how strong an edge is in the middle of a `3 x 3` block.

### Step 1: Inputs and output
Input: a `3 x 3` grayscale block. Output: `gx`, `gy`, and edge strength.

### Step 2: Rule
Multiply the block by each kernel below, add the 9 results to get `gx` and `gy`:

```text
Gx =       Gy =
-1  0  1   -1 -2 -1
-2  0  2    0  0  0
-1  0  1    1  2  1
```

Then `strength = sqrt(gx * gx + gy * gy)`.

### Step 3: Small example
```text
20  30 40
50  60 80
80  90 100
```
`gx = 100`, `gy = 240`, so `strength = 260`.

### Step 4: Python

In [14]:
import numpy as np

# TODO 1: 
def sobel_response(block: np.ndarray) -> tuple[float, float, float]:
    """Return gx, gy, and edge strength."""
    kernel_x = np.array([[-1, 0, 1],
                          [-2, 0, 2],
                          [-1, 0, 1]], dtype=np.float32)

    kernel_y = np.array([[-1, -2, -1],
                          [ 0,  0,  0],
                          [ 1,  2,  1]], dtype=np.float32)

    gx = np.sum(kernel_x * block)
    gy = np.sum(kernel_y * block)
    strength = np.sqrt(gx**2 + gy**2)

    return gx, gy, strength


print("Enter the 3x3 array, row by row (3 numbers separated by spaces):")
rows = []
for i in range(3):
    row_input = input(f"Row {i+1}: ")
    row = [float(x) for x in row_input.split()]
    rows.append(row)

user_block = np.array(rows, dtype=np.float32)

#the functionailty to input expected result is used because expected result will be different for each input, so by using this you can achieve the exact comparision
expected_gx = float(input("Enter expected gx: "))
expected_gy = float(input("Enter expected gy: "))
expected_strength = float(input("Enter expected edge strength: "))

gx, gy, strength = sobel_response(user_block)
print(f"\nArray:\n{user_block}")
print(f"gx = {gx}")
print(f"gy = {gy}")
print(f"edge strength = {strength}")
print(f"expected gx = {expected_gx}")
print(f"expected gy = {expected_gy}")
print(f"expected edge strength = {expected_strength}")

# TODO 2: 

assert gx == expected_gx and gy == expected_gy and strength == expected_strength
print("Problem 5 passed")

Enter the 3x3 array, row by row (3 numbers separated by spaces):

Array:
[[ 20.  30.  40.]
 [ 50.  60.  80.]
 [ 80.  90. 100.]]
gx = 100.0
gy = 240.0
edge strength = 260.0
expected gx = 100.0
expected gy = 240.0
expected edge strength = 260.0
Problem 5 passed
